### ISSUE TITLE
distance traveled is discarded on linux

### ISSUE THREAD

**Issue by jamesbt365** [nzbasic/Hand-Speed#3]
On linux when opentabletdriver is installed it is installed in /usr/share/OpenTabletDriver which is only writable by root, as opentabletdriver is not ran as root so anything that is saved there is discarded.

a better approach should be saving into the plugins folder or somewhere else or let the user choose with a box. 

Take a look at this:
https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/OpenTabletDriver.Desktop/AppInfo.cs#L31-L42

**Comment by nzbasic** [comment]
Fixed in Release 1.4.0 via adding an option to set the save directory
