### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Wolfman475** [nzbasic/Hand-Speed#4]
Hi um this is not exactly an issue and I am not a programmer but what is "OTD" where do I find "settings" and where are "plugins" located. Also i dont know the domain that I have to put in obs URL.

**Comment by nzbasic** [comment]
OTD is Open Tablet Driver https://opentabletdriver.net/
It is downloaded under plugins -> plugin manager -> nzbasic's Hand Speed
Then it is enabled in filters -> Hand Speed
The URL is opened in the browser when you enable the plugin

**Comment by Wolfman475** [comment]
om thank you so much
