### ISSUE TITLE
[Feature Request] Disable Link Open On OpenTabletDriver Startup

### ISSUE THREAD

**Issue by kesumin** [nzbasic/Hand-Speed#5]
Hi, thank you for your work on this plugin! It's useful and fun to look at statistics after working on a project or playing osu!game, but the only issue I'm having with it is whenever I launch OpenTabletDriver my browser starts or starts on whatever I'm currently looking at (ex youtube video) and makes me tab out to close it. It's just annoying after repetition since I've been using the plugin without looking at stats or running OBS for a few months now. 
I'd like the option to disable the link opening on startup in a checkbox with the filter settings. 

Thanks!

**Comment by nzbasic** [comment]
Option added in Release 1.4.0
